export type EcosystemNodeBlueprint = {
  id: string;
  label: string;
  homeX: number;
  homeY: number;
  mobileHomeX?: number;
  mobileHomeY?: number;
  hideOnMobile?: boolean;
  labelWidth: number;
  labelSide: "left" | "right" | "bottom";
  color: string;
  curveSide: 1 | -1;
  curveStrength: number;
  curveDrift: number;
  curvePhase: number;
};

export const ecosystemNodes: EcosystemNodeBlueprint[] = [
  {
    id: "travel",
    label: "Travel",
    homeX: 0.56,
    homeY: 0.17,
    mobileHomeX: 0.62,
    mobileHomeY: 0.24,
    labelWidth: 68,
    labelSide: "right",
    color: "#F6D77A",
    curveSide: 1,
    curveStrength: 18,
    curveDrift: 4,
    curvePhase: 0.4,
  },
  {
    id: "scarletwell",
    label: "ScarletWell",
    homeX: 0.69,
    homeY: 0.23,
    mobileHomeX: 0.76,
    mobileHomeY: 0.3,
    labelWidth: 100,
    labelSide: "right",
    color: "#F6E6A8",
    curveSide: -1,
    curveStrength: 16,
    curveDrift: 4,
    curvePhase: 0.8,
  },
  {
    id: "brown-research",
    label: "Brown Research",
    homeX: 0.82,
    homeY: 0.16,
    mobileHomeX: 0.78,
    mobileHomeY: 0.18,
    labelWidth: 118,
    labelSide: "right",
    color: "#CDEBD6",
    curveSide: 1,
    curveStrength: 17,
    curveDrift: 4,
    curvePhase: 1.1,
  },
  {
    id: "wellness-through-clay",
    label: "Wellness Through Clay",
    homeX: 0.91,
    homeY: 0.28,
    mobileHomeX: 0.84,
    mobileHomeY: 0.32,
    labelWidth: 156,
    labelSide: "left",
    color: "#C9B7F2",
    curveSide: -1,
    curveStrength: 20,
    curveDrift: 5,
    curvePhase: 1.5,
  },
  {
    id: "physics-teaching",
    label: "Physics Teaching",
    homeX: 0.93,
    homeY: 0.65,
    mobileHomeX: 0.84,
    mobileHomeY: 0.67,
    hideOnMobile: true,
    labelWidth: 116,
    labelSide: "left",
    color: "#F4C7B8",
    curveSide: -1,
    curveStrength: 18,
    curveDrift: 4,
    curvePhase: 2,
  },
  {
    id: "case-strategy",
    label: "Case Strategy",
    homeX: 0.72,
    homeY: 0.78,
    mobileHomeX: 0.72,
    mobileHomeY: 0.78,
    labelWidth: 102,
    labelSide: "right",
    color: "#B8E1C8",
    curveSide: 1,
    curveStrength: 16,
    curveDrift: 4,
    curvePhase: 2.2,
  },
  {
    id: "rutgers-research",
    label: "Rutgers Research",
    homeX: 0.58,
    homeY: 0.84,
    mobileHomeX: 0.56,
    mobileHomeY: 0.84,
    labelWidth: 126,
    labelSide: "bottom",
    color: "#D3E5A5",
    curveSide: 1,
    curveStrength: 16,
    curveDrift: 3,
    curvePhase: 2.6,
  },
  {
    id: "music",
    label: "Music",
    homeX: 0.33,
    homeY: 0.56,
    mobileHomeX: 0.26,
    mobileHomeY: 0.66,
    labelWidth: 62,
    labelSide: "left",
    color: "#AFCDF8",
    curveSide: -1,
    curveStrength: 19,
    curveDrift: 4,
    curvePhase: 2.9,
  },
  {
    id: "fashion",
    label: "Fashion",
    homeX: 0.29,
    homeY: 0.73,
    mobileHomeX: 0.22,
    mobileHomeY: 0.8,
    hideOnMobile: true,
    labelWidth: 74,
    labelSide: "left",
    color: "#F3AFCB",
    curveSide: 1,
    curveStrength: 22,
    curveDrift: 5,
    curvePhase: 3.8,
  },
  {
    id: "press-articles",
    label: "Press / Articles",
    homeX: 0.39,
    homeY: 0.28,
    mobileHomeX: 0.44,
    mobileHomeY: 0.38,
    labelWidth: 118,
    labelSide: "right",
    color: "#F6C58D",
    curveSide: 1,
    curveStrength: 18,
    curveDrift: 4,
    curvePhase: 4.5,
  },
  {
    id: "data-insights",
    label: "Data & Insights",
    homeX: 0.86,
    homeY: 0.48,
    mobileHomeX: 0.8,
    mobileHomeY: 0.54,
    labelWidth: 114,
    labelSide: "left",
    color: "#D8C4F2",
    curveSide: -1,
    curveStrength: 17,
    curveDrift: 4,
    curvePhase: 5.1,
  },
  {
    id: "scarletwell-studio",
    label: "ScarletWell Studio",
    homeX: 0.82,
    homeY: 0.58,
    mobileHomeX: 0.78,
    mobileHomeY: 0.6,
    labelWidth: 126,
    labelSide: "right",
    color: "#F0AFA0",
    curveSide: 1,
    curveStrength: 20,
    curveDrift: 5,
    curvePhase: 5.8,
  },
  {
    id: "sjms",
    label: "SJMS",
    homeX: 0.22,
    homeY: 0.43,
    mobileHomeX: 0.18,
    mobileHomeY: 0.54,
    hideOnMobile: true,
    labelWidth: 58,
    labelSide: "left",
    color: "#E7BFA8",
    curveSide: -1,
    curveStrength: 17,
    curveDrift: 4,
    curvePhase: 6.2,
  },
];
